config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :people
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
end

app/models/person.rb
class Person < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:firstname, :lastname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render "layouts/inc/head" %>

  <body id="rf">

    <%= render "layouts/inc/header" %>

    <%= render "layouts/inc/alert" %>

	  <!-- Main Content -->

    <div class="bg-white">

  	  <div class="container py-5">
  	    <%= yield %>
  	  </div>

    </div>

	  <!-- Footer -->

    <%= render "layouts/inc/footer" %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>

  <%= render "layouts/inc/head" %>

  <body id="rf" class="bg-dark">

    <!-- Main Content -->

    <div class="bg-dark">

      <div class="container py-5">
        <div class="row mt-3 mt-md-4 mt-lg-5">
          <div class="col-6 col-sm-5 col-md-4 col-lg-3 mx-auto text-center">
            <%= image_tag "poliferate_logo.svg", :class => "w-100" %>
          </div>
        </div>
        <div class="row mt-5">
          <div class="col-10 col-sm-8 col-md-6 col-lg-5 col-xl-4 mx-auto">
            <%= form_for(:user, :url => session_path(:user)) do |f| %>
              <%= f.text_field :email, placeholder: "email", class: "mb-4" %>
              <%= f.password_field :password, placeholder: "password", class: "mb-4" %>
              <%= f.check_box :remember_me, class: "d-none" %>
              <%= f.label :remember_me, class: "d-none" %>
              <%= button_tag( :class => "btn btn-danger btn-block mb-2") do %>
                Sign in <i class="far fa-arrow-circle-right fa-sm"></i>
              <% end %>
              <div class="small text-center">
                <%= link_to "forgot your password?", new_password_path(:user), class: "small d-block text-danger" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    </div>

    <!-- Javascript -->

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/layouts/inc/_alert.html.erb
<% if notice %>
	<div class="container">
		<div class="alert alert-info my-4"><span class="d-block"><%= notice %></span></div>
	</div>
<% end %>
<% if alert %>
	<div class="container">
		<div class="alert alert-danger my-4"><span class="d-block"><%= alert %></span></div>
	</div>
<% end %>

app/views/layouts/inc/_footer.html.erb
<footer class="py-5 bg-dark small">
	<div class="container">
		<div class="row">
			<div class="col-12 text-center small">
    		<span class="d-block small letter-spacing-2 text-primary text-uppercase font-headline text-uppercase"><i class="far fa-copyright"></i> <%= Time.now.strftime("%Y") %> Poliferate</span>
    	</div>
  	</div>
	</div>
</footer>

app/views/layouts/inc/_head.html.erb
<head>

	<meta name="viewport" content="width=device-width,initial-scale=1.0">

  <title>Poliferate</title>

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=Rubik:300,300i,700,700i" rel="stylesheet">
  
</head>

app/views/layouts/inc/_header.html.erb
<header class="bg-dark">
	<div class="container">
		<div class="nav navbar navbar-expand px-0">
  		<span class="text-uppercase font-headline font-weight-bold text-white small letter-spacing-1">Poliferate</span>
  		<ul class="nav ml-auto small text-uppercase letter-spacing-1">
  			<li class="nav-item small">
  				<%= link_to organizations_path, class: "nav-link text-light" do %>
  					<i class="far fa-building fa-sm"></i> Orgs
  				<% end %>
  			</li>
  			<li class="nav-item small">
  				<%= link_to people_path, class: "nav-link text-light" do %>
  					<i class="far fa-user fa-sm"></i> People
  				<% end %>
  			</li>
  			<li class="nav-item small">
  				<a href="#" class="nav-link text-light">
  					<i class="far fa-cog fa-sm"></i> Settings
  				</a>
  			</li>
  		</ul>
  	</div>
  </div>
</header>

app/views/layouts/organizations.html.erb
<!DOCTYPE html>
<html>

  <%= render "layouts/inc/head" %>

  <body id="rf">

    <%= render "layouts/inc/header" %>

    <%= render "layouts/inc/alert" %>

	  <!-- Main Content -->

    <div class="bg-white">

  	  <div class="container py-5">
        <h3 class="font-weight-normal letter-spacing-1 text-uppercase mb-2"><i class="fal fa-building"></i> Organizations</h3>
        <hr class="border-dark my-3">
  	    <%= yield %>
  	  </div>

    </div>

	  <!-- Footer -->

    <%= render "layouts/inc/footer" %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/layouts/people.html.erb
<!DOCTYPE html>
<html>

  <%= render "layouts/inc/head" %>

  <body id="rf">

    <%= render "layouts/inc/header" %>

    <%= render "layouts/inc/alert" %>

	  <!-- Main Content -->

    <div class="bg-white">

  	  <div class="container py-5">
        <h3 class="font-weight-normal letter-spacing-1 text-uppercase mb-2"><i class="fal fa-user"></i> People</h3>
        <hr class="border-dark my-3">
  	    <%= yield %>
  	  </div>

    </div>

	  <!-- Footer -->

    <%= render "layouts/inc/footer" %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </body>
</html>

app/views/organizations/_form.html.erb
<%= form_with(model: organization, local: true) do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :organization_name %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success btn-sm mt-4' %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<% unless @organizations.empty? %>

<div class="navbar nav p-0 my-3">
  <%= link_to new_organization_path, class: 'btn btn-success btn-sm ml-auto' do %>
    <i class="fa fa-plus"></i> Add Organization
  <% end %>
</div>

<hr class="border-dark my-3">

<% @organizations.each do |organization| %>

  <div class="card my-4">
    <div class="card-body row">
    
      <div class="col">
        <div>
          <span class="d-block font-headline lead"><%= organization.name %></span>
        </div>
      </div>
      <div class="col-auto flex-column">
        <div class="mb-1">
          <%= link_to organization, class: "btn btn-sm btn-info" do %>
            <i class="fa fa-fw fa-eye fa-sm "></i>
          <% end %>
        </div>
        <div class="mb-1">
          <%= link_to edit_organization_path(organization), class: "btn btn-sm btn-primary" do %>
            <i class="fa fa-fw fa-pencil fa-sm"></i>
          <% end %>
        </div>
        <div>
          <%= link_to organization, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm" do %>
          <i class="far fa-fw fa-trash fa-sm text-danger"></i>
          <% end %>
        </div>
      </div>
    
    </div>
  </div>

  <% end %>

  <%= link_to new_organization_path, class: 'btn btn-success' do %>
    <i class="fa fa-plus"></i> Add Organization
  <% end %>

<% else %>

  <div class="alert alert-info p-4">
    <span class="d-block text-center mb-3 lead">There are currently no organizations in your database.</span>
    <span class="d-block text-center">
      <%= link_to new_organization_path, class: 'btn btn-success' do %>
        <i class="fa fa-plus"></i> Add Organization
      <% end %>
    </span>
  </div>

<% end %>

app/views/organizations/new.html.erb
<div class="bg-light p-4">
	<h1>New Organization</h1>
	<%= render 'form', organization: @organization %>
</div>

<%= link_to organizations_path, class: "d-block text-secondary small mt-4" do %>
<i class="fa fa-angle-double-left fa-sm"></i> Back
<% end %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>

app/views/people/_form.html.erb
<div class="bg-light p-4">
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">

    <div class="field col-12 col-sm-6">
      <%= form.text_field :firstname, id: :person_firstname, placeholder: "first name" %>
    </div>

    <div class="field col-12 col-sm-6">
      <%= form.text_field :lastname, id: :person_lastname, placeholder: "last name" %>
    </div>

  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-success btn-sm mt-4' %>
  </div>
<% end %>
</div>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<% unless @people.empty? %>

<div class="navbar nav p-0 my-3">
  <%= link_to new_person_path, class: 'btn btn-success btn-sm ml-auto' do %>
    <i class="fa fa-plus"></i> Add person
  <% end %>
</div>

<hr class="border-dark my-3">

<div class="my-5">

  <% @people.each do |person| %>

    <div class="card border-secondary my-4">
      <div class="card-body row mx-0 px-0">
      
        <div class="col">
          <div>
            <span class="d-block font-headline">
              <span class="small">
                <i class="far fa-dot-circle fa-sm align-text-top text-muted"></i>
              </span>
              <span class="lead"><%= person.firstname %> <%= person.lastname %></span></span>
          </div>
        </div>
        <div class="col-auto flex-column card border-top-0 border-bottom-0 border-right-0">
          <div class="mb-2">
            <%= link_to person, class: "btn btn-sm btn-info" do %>
              <i class="fa fa-fw fa-eye fa-sm "></i>
            <% end %>
          </div>
          <div class="mb-2">
            <%= link_to edit_person_path(person), class: "btn btn-sm btn-primary" do %>
              <i class="fa fa-fw fa-pencil fa-sm"></i>
            <% end %>
          </div>
          <div>
            <%= link_to person, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm" do %>
            <i class="far fa-fw fa-trash fa-sm text-danger"></i>
            <% end %>
          </div>
        </div>
      
      </div>
    </div>

    <% end %>

  <% else %>

    <div class="alert alert-info p-4">
      <span class="d-block text-center mb-3 lead">There are currently no people in your database.</span>
      <span class="d-block text-center">
        <%= link_to new_person_path, class: 'btn btn-success' do %>
          <i class="fa fa-plus"></i> Add person
        <% end %>
      </span>
    </div>

  <% end %>

</div>

<%= link_to new_person_path, class: 'btn btn-success' do %>
  <i class="fa fa-plus"></i> Add person
<% end %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>